# Generated by Django 4.0 on 2021-12-29 15:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attends',
            name='course_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='上课时间'),
        ),
        migrations.AlterField(
            model_name='reserveequipment',
            name='due_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 29, 16, 56, 51, 519766, tzinfo=utc), verbose_name='过期时间'),
        ),
    ]
