# Generated by Django 4.0 on 2021-12-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyadmin_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyadminemailverifyrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tyadminsyslog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
